### ISSUE TITLE
pip install python-musicbrainz2 leads to "Non-zero exit code"

### ISSUE THREAD

**Issue by jboegeholz** [mineo/python-musicbrainz2#1]
I've tried to install python-musicbrainz2 via PyCharm and via command line but always get the following error:

CLI
Collecting python-musicbrainz2
  Could not find a version that satisfies the requirement python-musicbrainz2 (from versions: )
No matching distribution found for python-musicbrainz2

PyCharm
Command output
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking python-musicbrainz2
  Could not find any downloads that satisfy the requirement python-musicbrainz2
Cleaning up...
No distributions at all found for python-musicbrainz2
Storing debug log for failure in /Users/jornbogeholz/.pip/pip.log

Environment
Mac OS X 10.6.8
pip 8.1.2
Python 2.7.9

**Comment by mineo** [comment]
The [web service](https://beta.musicbrainz.org/doc/Development/XML_Web_Service/Version_1) used by python-musicbrainz2 is deprecated, please don't use it.

I'm not sure what's wrong with the distribution of python-musicbrainz2 on PyPI, but it looks like no source files have been uploaded. I'm not the maintainer of this package and not the owner of the entry on PyPI, so I can't help you with this.
